spring:
  application:
    name: milkyway

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{db address}:{db port}/{database name}
    username: {username}
    password: {password}


springdoc:
  swagger-ui:
    path: /api-docs/
    disable-swagger-default-url: true


payment:
  secret-key: {toss secret-key}
  base-url: https://api.tosspayments.com/v1/payments
  auth-header-prefix: Basic